name: Lint
on:
  workflow_dispatch:
  push:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun.sh
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install
      - run: bun lint
